// create
export const CREATE_COMMUNITY_SUCCESS = "CREATE_COMMUNITY_SUCCESS";

// delete
export const DELETE_COMMUNITY_SUCCESS = "DELETE_COMMUNITY_SUCCESS";

// update
export const UPDATE_COMMUNITY_SUCCESS = "UPDATE_COMMUNITY_SUCCESS";

// get
export const GET_COMMUNITIES_SUCCESS = "GET_COMMUNITIES_SUCCESS";
