// create
export const CREATE_BOARD_PENDING = "CREATE_BOARD_PENDING";
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS";
export const CREATE_BOARD_FAILURE = "CREATE_BOARD_FAILURE";

// delete
export const DELETE_BOARD_PENDING = "DELETE_BOARD_PENDING";
export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS";
export const DELETE_BOARD_FAILURE = "DELETE_BOARD_FAILURE";

// update
export const UPDATE_BOARD_PENDING = "UPDATE_BOARD_PENDING";
export const UPDATE_BOARD_SUCCESS = "UPDATE_BOARD_SUCCESS";
export const UPDATE_BOARD_FAILURE = "UPDATE_BOARD_FAILURE";

// get
export const GET_BOARD_PENDING = "GET_BOARD_PENDING";
export const GET_BOARD_SUCCESS = "GET_BOARD_SUCCESS";
export const GET_BOARD_FAILURE = "GET_BOARD_FAILURE";
