// create
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS";

// delete
export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS";

// update
export const UPDATE_BOARD_SUCCESS = "UPDATE_BOARD_SUCCESS";

// get
export const GET_BOARD_SUCCESS = "GET_BOARD_SUCCESS";
