// create payment
export const CREATE_PAYMENT_PENDING = "CREATE_PAYMENT_PENDING";
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_FAILURE = "CREATE_PAYMENT_FAILURE";

// confirm payment
export const CONFIRM_PAYMENT_PENDING = "CONFIRM_PAYMENT_PENDING";
export const CONFIRM_PAYMENT_SUCCESS = "CONFIRM_PAYMENT_SUCCESS";
export const CONFIRM_PAYMENT_FAILURE = "CONFIRM_PAYMENT_FAILURE";

// begin payment
export const BEGIN_PAYMENT_PENDING = "BEGIN_PAYMENT_PENDING";
export const BEGIN_PAYMENT_SUCCESS = "BEGIN_PAYMENT_SUCCESS";
export const BEGIN_PAYMENT_FAILURE = "BEGIN_PAYMENT_FAILURE";

// complete payment
export const COMPLETE_PAYMENT_PENDING = "COMPLETE_PAYMENT_PENDING";
export const COMPLETE_PAYMENT_SUCCESS = "COMPLETE_PAYMENT_SUCCESS";
export const COMPLETE_PAYMENT_FAILURE = "COMPLETE_PAYMENT_FAILURE";
