// login
export const COMMUNITY_STATS_PENDING = "COMMUNITY_STATS_PENDING";
export const COMMUNITY_STATS_SUCCESS = "COMMUNITY_STATS_SUCCESS";
export const COMMUNITY_STATS_FAILURE = "COMMUNITY_STATS_FAILURE";
